name: example
description: A new Flutter project.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_spinwheel:
    path: ../
  carousel_slider: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/cat.jpg
    - assets/images/dog.jpg
    - assets/images/budgie.jpg
    - assets/images/goldfish.jpg
    - assets/images/car.jpg
    - assets/images/bike.jpg
    - assets/images/other.jpg
